---
title: "Class activity solutions"
format: html
editor: visual
author: "Ciaran Evans"
---

1. 

```{r, echo=T}
x <- rep(NA, 100)
```

2. 

```{r, echo=T}
x <- rep(0, 3)
```

3. 

```{r, echo=T}
x <- seq(0, 3, 0.01)
```

4. 

```{r, echo=T}
x <- seq(0, 3, 0.01)
x[23]
```

5.

```{r, echo=T}
x <- seq(0, 3, 0.01)
sqrt_x <- rep(NA, length(x))
for(i in 1:length(x)){
  sqrt_x[i] <- sqrt(x[i])
}
```

6. 

```{r, echo=T}
x <- seq(0, 3, 0.01)
sqrt_x <- sqrt(x)
```

7. 

```{r, echo=T}
x <- sample(1:100, 10, replace=FALSE)
```

8.

```{r, echo=T}
x <- sample(-2:2, 10, replace=TRUE)
```

9. 

```{r, echo=T}
x <- rnorm(1000, mean=3, sd=sqrt(11))
```

10.

```{r, echo=T}
exp_model <- function(n, beta0, beta1){
  x <- rnorm(n)
  y <- beta0 * x^beta1
  plot(x, y)
}
```

11.

```{r, echo=T}
exp_model <- function(n, beta0, beta1){
  x <- rnorm(n)
  y <- beta0 * x^beta1
  return(list(x, y))
}
```

12. There are many possible solutions; here is one example:

```{r, echo=T}
x <- list("a", list("a", c(2, 7, 9)))
x[[2]][[2]]
```

13. Because `x[1]` is a list (containing a function), *not* a function

14. 

```{r, echo=T}
x <- list(function(n){return(rnorm(n, mean=0, sd=3))},
          function(n){return(runif(n, min=0, max=1))})

x[[1]](10)
```




